### ISSUE TITLE
Landing page for Hugo Indonesia Website

### ISSUE THREAD

**Issue by ardianta** [gohugoid/gohugoid-web#3]
This is Hugo Indonesia community website: https://gohugoid.github.io/
Need help to build hugo template using bootstrap 4.

TODO:

- [x] Navbar section: Home, About, Blog, Events
- [x] Hero section: Hugo Indonesia
- [x] About Section: What is Hugo
- [x] Showcase Galleries section
- [x] News/Blog post list section
- [x] Footer Section

**Comment by PROTechThor** [comment]
I got this.

**Comment by yudyananda** [comment]
harus botstrap?

**Comment by ardianta** [comment]
Tidak harus, Bulma dan framework yang lain juga bisa. Mana yang tercepat, hehe
